### ISSUE TITLE
(setq hide-mode-line-excluded-modes nil) does not disable the modelines in Fundamental mode

### ISSUE THREAD

**Issue by JiaweiChenC** [hlissner/emacs-hide-mode-line#11]
### What did you expect to happen?

After I enable global-hide-mode-line mode all modeline in all buffers should disappear.

### What actually happened?

After enable global-hide-mode-line-mode, a new buffer created with Fundamental mode will still have the modeline

### Steps to reproduce

I think (set hide-mode-line-exclude-modes nil) does not work as expected. For example, given the test code:

```elisp
;; test.el
(package-initialize)

;; straight.el initialization
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

;; Location of my use-package git clone
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/use-package/")
(require 'use-package)

(use-package hide-mode-line
  :ensure t)

(use-package eglot
  :ensure t)

(setq hide-mode-line-excluded-modes nil)

(add-hook 'python-mode-hook 'eglot-ensure)

(global-hide-mode-line-mode)
```
First open emacs with:

```shell
emacs -Q -l test.el
```

Then use
C-x C-f to find the test.py under the directory.

Then use
C-x C-b to find the eglot buffer, I can still see the modeline
![image](https://github.com/user-attachments/assets/4e08ec51-40e7-429c-aa7e-a0df7a848db3)

Since I am using doom emacs, this issue is obvious when I use the scratch buffer, after I enable the global-hide-mode line mode, when the second time I do "spc x", the mode line will show up.
![hide-mode-line-bug](https://github.com/user-attachments/assets/9a40296f-827d-4f3e-ab98-fd3f5ad79892)

Thank you for your assisstance!

### Package commit

bc5d293576c5e08c29e694078b96a5ed85631942

### System Information

https://pastebin.com/7CiVuQVg

**Comment by hlissner** [comment]
As of ab699fd this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by JiaweiChenC** [comment]
Thank you for your response! However, this seems does not solve the issue. 

A simple test could be if I enable (global-hide-mode-line-mode) in the config file, then use space x, the modeline is still there. 

![hide-mode-line-bug-2](https://github.com/user-attachments/assets/699850b2-032d-4a55-9373-73662d6137e5)

Similar issue could be found if I open a vterm window using `space o t`, then open the vterm buffer using `C-x 1`, I can still see the modeline there.

Let me know if you can reproduce the issue on your end, or it might be a issue in my config file (I am using doom emacs @29.4). This might be due to that special buffers are treated differently in emacs? 

A simple workaround might be setting scratch buffer as popup 
``` elisp
(after! popup
  (set-popup-rule! "^\\*doom:scratch\\*" :size 0.3 :quit t :select t :ttl 5))
```
However, I think it would be nice if there is a clean way to disable the modeline in these special buffers.

Thank you again for your time!

**Comment by hlissner** [comment]
I can't reproduce any of these cases in vanilla Doom. `global-hide-mode-line-mode` (whether I activate with `M-x` or by adding `(global-hide-mode-line-mode +1)` to my `$DOOMDIR/config.el`) suppresses the mode-line in vterm (`SPC o t`), Doom's scratch buffer (`SPC x`), and eshell (`SPC o e`), as far as I can tell. Modes that take control over their own mode-lines (like dired+dirvish and Magit) naturally override this package, but those are outliers.

**Comment by hlissner** [comment]
I notice you have a `global-hide-mode-line-mode` entry in your `custom-file`. This may be having a negative effect. Try removing it. 

> This might be due to that special buffers are treated differently in emacs?

Global modes target all buffers, even special ones, so as long as you have `(setq hide-mode-line-exclude-modes nil)` in your config (and are using the latest version of this package), it should work for you.

**Comment by JiaweiChenC** [comment]
You are right. I do notice that setting global-hide-mode-line-mode in the custom-file will cause problems. I try to use (global-hide-mode-line-mode) in custom-file because I am trying to use other modelines like [nano modeline](https://github.com/rougier/nano-modeline), which set the modeline at the top of the frame and want to disable the modeline at the bottom at the init of emacs. 

Actually, if I set global-hide-mode-line mode using `(add-hook 'emacs-startup-hook #'global-hide-mode-line-mode)` the behavior will be similar to set it manually after init. 

However, the issue is that some new buffers created will have modeline with it, for example (a vanilla doom build just now with unpin! hide-mode-line), we can see the mode line will show up after I enter C-x-1. 
![hide-mode-line-issue](https://github.com/user-attachments/assets/8d4fd411-e9fa-4152-9d68-e7bf48ba0a2c)

As I said, since I am using the modeline at the top, so I can see two modelines in this case which is a little bit wired.

Anyway, thank you for you time and patience!

**Comment by hlissner** [comment]
Ooh, it's because of `C-x 1`. Once you "raise" a popup into a normal window, it disables `+popup-buffer-mode`, which *re-*disables `hide-mode-line` (because popups disable them by default).

In that case, it's a bug in Doom's popup module rather than this package. I'd recommend using `SPC o T` (`+vterm/here`) instead of `SPC o t` + `C-x 1`. It will open vterm in the whole window. Same goes for `SPC b X` (open scratch buffer in current window) instead of `SPC x` (opens scratch buffer in popup).

**Comment by JiaweiChenC** [comment]
Got it, thanks!

**Comment by hlissner** [comment]
Another workaround, while I experiment with a fix:

```elisp
;;; add to $DOOMDIR/config.el
(defadvice! fixed-+popup-unset-modeline-on-disable-h (fn &rest args)
  :around #'+popup-unset-modeline-on-disable-h
  (unless (bound-and-true-p global-hide-mode-line-mode)
    (apply fn args)))
```

**Comment by JiaweiChenC** [comment]
Perfect! That solves everything!
